CREATE TABLE RUTAS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBRE TEXT NOT NULL,
    RUTA TEXT
);

INSERT INTO RUTAS (NOMBRE, RUTA) VALUES ('DACXANALISTA', '');
INSERT INTO RUTAS (NOMBRE, RUTA) VALUES ('MODELO', '');
INSERT INTO RUTAS (NOMBRE, RUTA) VALUES ('ZFIR60', '');
INSERT INTO RUTAS (NOMBRE, RUTA) VALUES ('SMS_CCD', '');
INSERT INTO RUTAS (NOMBRE, RUTA) VALUES ('VACACIONES', '');

SELECT * FROM RUTAS;